language: ruby
rvm:
  - 2.6.1
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler

script: ./scripts/cibuild

deploy:
  provider: s3
  access_key_id: 
    secure: "hpex9olhkuQOXMybEOqUklCLiy/8cLTg6zEZcG3p01nKtFgj4S8/Ir3hXbXARzJ4GQ3eQTAsZla4lkVG9HbACHcB/1PnvyCXm3EVvqmmE1mycnL0tvTLn9KM78muP3ZkDkBBNuKz+RSZG5wk6lEdyoWb4phI0z6C+YUHXEH6jdDr0C38phnB7oHym44DNcwE/5jU63zTojENSBRDLC9FnGXzrG3bluMbqVNAog/4NNpHRpYgd0vdmkdJMnLjRyB5OZnmq3WZgoMMHak48+Fal0Qd54DwB3EqhNLKtwWAtAWzDfC+4fNdSURZBEdr32KOlxyP4DyBL+/pn84Puu2Do2IVLcWa3kzgbPMoQb4Dcsug3EwPoLkHvfuiGYr/H8qSejjNOIcIyGTuZK2lQvO2oPwZmOaRO4vK0+2Uoz1Pbm00zb7u4n4t5gPQ6S1sVlbo913G0hsGzisuFpyqTGHt9MLnZ5Uv+xY3iO76ZbT83wiYqHSk23af2tk75sUhQhwVj/Kjrx/1Dpnx7m9phQqpagjGm+zFW/X+BPOjz42payOSCO41GgWiT4n7xWP/A08gK3X1bf1tKyOx+JEgBAG05gB2Bm6cpFYzKItxOK559YS5IMJXUL5VZYO1yWcZR3J1XK6Kh1d4+z40wvzXWu8sSAOsDD9iwSZl1lV6fwWlx5o="
  secret_access_key:
    secure: "LxtnxP/hj2QEzD3wqPjYBqPya9JWWaKJwY0z3UZ8gylJAhWzFtkEeeBssZpcBv1kGK+NCTT0lMidJty+0PYj4pFfWo6zTRDgX5Rp7qu4u23M/bLHIz1xZLwwRWNXA4cMZ5i4P29ke5ss1Spz01UK0vA6FVVSyJGZ/GtA8cxH9p1gVXD6ycMVuLuaqRHPxOd7KV3IfKs1i13/VA86YyllYOH4m3ROPPgb8Uy9oNKM9NdSe9eQCyHuyE6scp+CWMBJfeY2K8lre8IP8rQ07aTI096VXPogYmaVftPc2So+NkchviOkym2GIkDIMgtC+lc6RqOD/An8YRPVJKEnoxDkVW4ztZWpEad2ZQYa5Jc2j3QlAzTNZrQYa5CmcNWWraS1QbXcCPPuckESKqJtk7Z1y38BIrfHCgXVLMEfRgHQgg003wFNln063KA/Lz+wPom58FGxvnxkaoYTDaxRsCGBLRk1eZsbhDJi2GulS5xhqXk71eb1yyk4jUkcyqw+ePhjVjWtMcnO02Z2SuPlH/rqnTkSaE9A7Sl+EqxjtyksPO8TlhVZfEwtlshFdORLmcilHkJ8d2kvbPzr92l2RgrTTj6j5I59y5/C4abZnMVTK9SFWZqIW8X1SKCdBut6I2tDbZ9uQ7Z+h99ZkFjlx4xcxG6H5e7WJjMrZ8QrXLCTXLY="
  bucket: "annconsulting.co.uk"
  region: "eu-west-2"
  local_dir: "_site"
  skip_cleanup: true

notifications:
  email: false

