title: Adam Narkonski - Contractor
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    Helyo what are you doing?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://annconsulting.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor
