title: ANN Consulting 
description: 
author: Adam Narkunski
github: https://github.com/wat-izz
about: I'm Programmer for Python & Java. I've made quite a few web apps, especially on Django.
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "#"
    - icon: fa-github
      link: "https://github.com/agusmakmun"

urls:
    - text: About Me
      url: /about/

url: "https://annconsulting.co.uk"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

